spring.application.name=financeiro
api.gateway.url=${API_GATEWAY_URL}

# ============================
# S3
# ============================
s3.bucket-name=${S3_BUCKET_NAME:prestobr-repromaq-dev-datalake}
s3.endpoint-url=${S3_ENDPOINT_URL:https://s3.us-east-2.amazonaws.com}
s3.access-key=${S3_ACCESS_KEY}
s3.secret-key=${S3_SECRET_KEY}
s3.region=${S3_REGION:us-east-2}

# ============================
# DataLake
# ============================
datalake.gold-account-payable-base-prefix=${DATALAKE_GOLD_CONTAS_PAGAR_PREFIX}
datalake.gold-account-receivable-base-prefix=${DATALAKE_GOLD_CONTAS_RECEBER_PREFIX}
datalake.gold-account-receipt-base-prefix=${DATALAKE_GOLD_RECEBIMENTO_PREFIX}
datalake.gold-account-payment-base-prefix=${DATALAKE_GOLD_PAGAMENTO_PREFIX}

# ============================
# Cache
# ============================
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=1,expireAfterWrite=3600s

# ============================
# Financeiro
# ============================
financeiro.account-payable.anonymize-data=false
financeiro.account-receivable.anonymize-data=false
financeiro.account-receipt.anonymize-data=false
financeiro.account-payment.anonymize-data=false

# ============================
# SpringDoc
# ============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

# ============================
# Actuator / Prometheus
# ============================
management.endpoints.web.exposure.include=health,prometheus