package com.prestobr.financeiro.dto.response;

import com.prestobr.financeiro.domain.entity.AccountPayable;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Schema(name = "Response.AccountPayable", description = "Dados de um AccountPayable")
public record AccountPayableResponse(
                String codigoTitulo,
                String codigoCompra,
                String codEmpresa,
                String nomeEmpresa,
                String codFornecedor,
                String nomeFornecedor,
                String fantasiaFornecedor,
                String cnpjFornecedor,
                String cpfFornecedor,
                String transportador,
                String nomeTransportador,
                String prestador,
                String nomePrestador,
                String statusPagamento,
                String nomeStatus,
                String tipoDocumento,
                String nomeTipoDocumento,
                String codCentroCusto,
                String nomeCentroCusto,
                String codSubcentroCusto,
                String nomeSubcentroCusto,
                String planoConta,
                String nomePlanoConta,
                String codSetor,
                String contrato,
                LocalDateTime dataEmissao,
                LocalDateTime dataVencimento,
                LocalDateTime dataEntrada,
                LocalDateTime dataCadastro,
                LocalDateTime dataAlteracao,
                BigDecimal valorTitulo,
                BigDecimal valorPago,
                BigDecimal valorSaldo,
                BigDecimal valorBruto,
                BigDecimal valorDesconto,
                BigDecimal valorAcrescimo,
                BigDecimal valorMovimento,
                BigDecimal valorOutras,
                BigDecimal atualizacaoMonetaria,
                Boolean isPagoTotal,
                Boolean isProvisao,
                String situacaoTitulo,
                String tipoTitulo,
                String operacao,
                String formaPagamento,
                String opcaoPagamento,
                String numeroParcela,
                String mesCompetencia,
                String periodo,
                String periodoApuracao,
                String periodoReferencia,
                Integer anoCalculo,
                Integer diasAtraso,
                String historico,
                String observacao,
                String documentoContribuinte,
                String inscricaoEstadual,
                String codMunicipio,
                String uf,
                Integer contadorPagamento,
                String operadorCadastro,
                String operadorAlteracao,
                LocalDateTime snapshotDatetime
) {
    public static AccountPayableResponse from(AccountPayable ap) {
        return new AccountPayableResponse(
                ap.getCodigoTitulo(),
                ap.getCodigoCompra(),
                ap.getCodEmpresa(),
                ap.getNomeEmpresa(),
                ap.getCodFornecedor(),
                ap.getNomeFornecedor(),
                ap.getFantasiaFornecedor(),
                ap.getCnpjFornecedor(),
                ap.getCpfFornecedor(),
                ap.getTransportador(),
                ap.getNomeTransportador(),
                ap.getPrestador(),
                ap.getNomePrestador(),
                ap.getStatusPagamento(),
                ap.getNomeStatus(),
                ap.getTipoDocumento(),
                ap.getNomeTipoDocumento(),
                ap.getCodCentroCusto(),
                ap.getNomeCentroCusto(),
                ap.getCodSubcentroCusto(),
                ap.getNomeSubcentroCusto(),
                ap.getPlanoConta(),
                ap.getNomePlanoConta(),
                ap.getCodSetor(),
                ap.getContrato(),
                ap.getDataEmissao(),
                ap.getDataVencimento(),
                ap.getDataEntrada(),
                ap.getDataCadastro(),
                ap.getDataAlteracao(),
                ap.getValorTitulo(),
                ap.getValorPago(),
                ap.getValorSaldo(),
                ap.getValorBruto(),
                ap.getValorDesconto(),
                ap.getValorAcrescimo(),
                ap.getValorMovimento(),
                ap.getValorOutras(),
                ap.getAtualizacaoMonetaria(),
                ap.getIsPagoTotal(),
                ap.getIsProvisao(),
                ap.getSituacaoTitulo(),
                ap.getTipoTitulo(),
                ap.getOperacao(),
                ap.getFormaPagamento(),
                ap.getOpcaoPagamento(),
                ap.getNumeroParcela(),
                ap.getMesCompetencia(),
                ap.getPeriodo(),
                ap.getPeriodoApuracao(),
                ap.getPeriodoReferencia(),
                ap.getAnoCalculo(),
                ap.getDiasAtraso(),
                ap.getHistorico(),
                ap.getObservacao(),
                ap.getDocumentoContribuinte(),
                ap.getInscricaoEstadual(),
                ap.getCodMunicipio(),
                ap.getUf(),
                ap.getContadorPagamento(),
                ap.getOperadorCadastro(),
                ap.getOperadorAlteracao(),
                ap.getSnapshotDatetime()
        );
    }
}
